### ISSUE TITLE
Cannot convert 2dxr files

### ISSUE THREAD

**Issue by DJANDREAJAPAN** [mon/2dxTools#5]
I tried your 2dx file extractor, but it doesn't work when I try to use the 2dxr files and on the 1r files.
For me, I want to compile the song's key sound file and the unassigned BGM file to create a complete song, plus extracting the preview 2dx data to wav file.
Also, I'm using the cmd prompt with authenciated version and the normal version to test if it works.
Would you tell me how to do this task please?
Thanks.

**Comment by mon** [comment]
r files are encrypted files from IIDX Infinitas. They will need to be decrypted.
